modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/TenshiLib/issues"
[[mods]]
modId="tenshilib"
version="${version}"
displayName="TenshiLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tenshilib"
logoFile="icon.png"
authors="Flemmli97"
description='''Core and library mod for most of my mods. Contains useful hooks and functions'''
[[dependencies.tenshilib]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"
