org.gradle.jvmargs=-Xmx3G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
neoForm_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
# NeoForge Properties
neoforge_loader_version=2
neoforge_version=21.1.4
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=2.3.0.b
maven_group=io.github.flemmli97
mod_id=tenshilib
mod_author=flemmli97

# Dependencies
fabric_api_version=0.116.4+1.21.1
sbl_version=1.16.10

# Curse properties
curseforge_versions=1.21.1, Java 21
curseforge_page_fabric=https://www.curseforge.com/minecraft/mc-mods/tenshilib-fabric
curseforge_id_fabric=552662
curseforge_dep_fabric=fabric-api
curseforge_page_neoforge=https://www.curseforge.com/minecraft/mc-mods/tenshilib
curseforge_id_neoforge=312040
curseforge_dep_neoforge=
modrinth_versions=1.21.1
modrinth_page=https://modrinth.com/mod/tenshilib
modrinth_id=P2rffivS
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=TenshiLib
full_changelog=https://github.com/Flemmli97/TenshiLib/blob/1.21/Changelog.md
discord_role=1129751672009273467
