modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/TenshiLib/issues"
displayURL="https://github.com/Flemmli97/TenshiLib"
# logoFile=""
credits=""
authors="Flemmli97"
[[mods]] 
  modId="tenshilib"
  version="${file.jarVersion}"
  displayName="TenshiLib"
  # updateJSONURL=""
  authors="Flemmli97"
  description='''Core and library mod for most of my mods. Contains useful hooks and functions'''
[[dependencies.tenshilib]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.2,)"
  ordering="NONE"
  side="BOTH"
