package com.flemmli97.tenshilib.common.world.structure;

/**
 * FLOATING = NOTHING REPLACEBELOW = REPLACES AIR SPACE BELOW IT GROUNDALIGNED = ALIGNES WITH THE GROUND (LIKE VILLAGER
 * PATHS ETC.)
 */
public enum GenerationType {

    FLOATING, REPLACEBELOW, GROUNDALIGNED;
}
